# Generated by Django 4.2.7 on 2023-12-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookface', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
