# Generated by Django 4.2.7 on 2023-11-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('subcategory', models.TextField()),
                ('item', models.TextField()),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('price', models.TextField()),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
