# Generated by Django 4.2.7 on 2023-11-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_menu_delete_mymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
    ]
