# Generated by Django 4.2.7 on 2023-11-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_menu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'managed': False},
        ),
    ]
